# Generated by Django 5.2.14 on 2026-08-12 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('seo', 'SEO Blog'), ('technical', 'Technical Article'), ('tutorial', 'Tutorial / How-To'), ('academic', 'Academic Article'), ('news', 'News Article'), ('explainer', 'Explainer Article'), ('case_study', 'Case Study'), ('product_review', 'Product Review'), ('documentation', 'Documentation'), ('linkedin', 'LinkedIn / Social'), ('general', 'General')], default='general', max_length=50)),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField()),
                ('variables', models.JSONField(default=list, help_text="List of variable descriptors e.g. [{'name': 'topic', 'label': 'Topic', 'type': 'text'}]")),
                ('version', models.IntegerField(default=1)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('target_audience', models.CharField(default='General Audience', max_length=150)),
                ('tone', models.CharField(default='Professional', max_length=100)),
                ('language', models.CharField(default='English', max_length=50)),
                ('target_length', models.CharField(default='Medium (~1000 words)', max_length=50)),
                ('variables_values', models.JSONField(blank=True, default=dict)),
                ('outline', models.TextField(blank=True, default='')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('generation_pipeline_used', models.CharField(choices=[('direct', 'Direct Generation'), ('multi_stage', 'Multi-Stage Pipeline (Outline -> Article -> Eval -> Refine)')], default='direct', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_articles', to='api.prompttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.IntegerField(default=85)),
                ('structure_score', models.IntegerField(default=85)),
                ('readability_score', models.IntegerField(default=85)),
                ('completeness_score', models.IntegerField(default=85)),
                ('seo_score', models.IntegerField(default=85)),
                ('overall_score', models.IntegerField(default=85)),
                ('feedback_json', models.JSONField(default=dict, help_text='Strengths, weaknesses, actionable recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='api.article')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(default='generate', max_length=50)),
                ('prompt_used', models.TextField()),
                ('system_prompt_used', models.TextField()),
                ('model_name', models.CharField(default='gemini-2.5-flash', max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.article')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField()),
                ('variables', models.JSONField(default=list)),
                ('changelog', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='api.prompttemplate')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('template', 'version')},
            },
        ),
    ]
